### ISSUE TITLE
Bluemix installation failed due to deprecated bcrypt package

### ISSUE THREAD

**Issue by andrefgj** [gabrieljesus/node-red-contrib-ibm-maximo-oslc-api#2]
Bluemix installation is failing due to deprecated bcrypt package:

```
npm WARN deprecated bcrypt@1.0.3: bcrypt < v2.0.0 is susceptible to bcrypt wrap-around bug. Upgrade to bcrypt >= v2.0.0 for improved support for newer bcrypt hashes
Killed
```

**Comment by gabrieljesus** [comment]
Hi Andre,

it seems to be a Bluemix npm problem. I've installed node-red (0.19.2) and node-red-contrib-ibm-maximo-oslc-api (0.1.4) from scratch and everything looks fine. This is my log:

```shell
5 Sep 09:13:24 - [info] Installing module: node-red-contrib-ibm-maximo-oslc-api, version: 0.1.4
5 Sep 09:13:48 - [info] Installed module: node-red-contrib-ibm-maximo-oslc-api
5 Sep 09:13:48 - [info] Added node types:
5 Sep 09:13:48 - [info]  - node-red-contrib-ibm-maximo-oslc-api:maximoConnection
5 Sep 09:13:48 - [info]  - node-red-contrib-ibm-maximo-oslc-api:retrieve
5 Sep 09:13:48 - [info]  - node-red-contrib-ibm-maximo-oslc-api:create
5 Sep 09:13:48 - [info]  - node-red-contrib-ibm-maximo-oslc-api:update
5 Sep 09:13:48 - [info]  - node-red-contrib-ibm-maximo-oslc-api:delete
```

Do you have your node-red log?

Thanks

GJ

**Comment by andrefgj** [comment]
Hi Gab.

The log is the one in the description.

https://github.com/gabrieljesus/node-red-contrib-ibm-maximo-oslc-api/issues/2#issue-357177662

**Comment by gabrieljesus** [comment]
Hi Andre,

I mean the complete node-red log. Hopefully there are more information before and after that message to help us.

Thanks in advance,

GJ
